name: Changelog Check

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main

jobs:
  changelog-check:
    name: Check Changelog Update
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'no-changelog')"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Check for CHANGELOG updates
        run: |
          if git diff --name-only origin/main..HEAD | grep -q "CHANGELOG.md"; then
            echo "Changelog was updated. Great job!"
            exit 0
          else
            echo "Error: CHANGELOG.md was not updated."
            echo "Please update the CHANGELOG.md file to include your changes."
            echo "If this PR doesn't require a changelog entry, please add the 'no-changelog' label."
            exit 1
          fi
